require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0
  DisplayStyleGuide: true
  Include:
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/jobs/*'
    - 'app/mailers/*'
    - 'app/models/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'lib/**/*'
    - 'Rakefile'
  Exclude:
    - 'app/assets/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'docs/**/*'
    - 'engines/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 95

MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

BlockLength:
  Max: 70

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  EnforcedStyle: brackets
